-- ========================================
-- 購買機能用テーブル定義 (DDL)
-- ========================================
-- 命名規則:
--   スキーマ: SAMPLE (プロジェクト名に合わせる)
--   マスタテーブル: TM_XXX (Table Master)
--   トランザクションテーブル: TT_XXX (Table Transaction)
-- ========================================

-- スキーマ作成
CREATE SCHEMA IF NOT EXISTS SAMPLE;

-- 既存テーブルの削除
DROP TABLE IF EXISTS SAMPLE.TT_CART CASCADE;
DROP TABLE IF EXISTS SAMPLE.TM_COMPANY_PRODUCT_AUTH CASCADE;
DROP TABLE IF EXISTS SAMPLE.TM_PRODUCT CASCADE;
DROP TABLE IF EXISTS SAMPLE.TM_USER_COMPANY CASCADE;
DROP TABLE IF EXISTS SAMPLE.TM_COMPANY CASCADE;
DROP TABLE IF EXISTS SAMPLE.TM_USER CASCADE;

-- ユーザマスタ
DROP TABLE IF EXISTS SAMPLE.TM_USER CASCADE;
CREATE TABLE SAMPLE.TM_USER (
    USER_ID VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
    ACCOUNT_LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    DEL_FLG BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50)
);

COMMENT ON TABLE SAMPLE.TM_USER IS 'ユーザマスタ';
COMMENT ON COLUMN SAMPLE.TM_USER.USER_ID IS 'ユーザID（PK）';
COMMENT ON COLUMN SAMPLE.TM_USER.PASSWORD IS 'パスワード（BCrypt）';
COMMENT ON COLUMN SAMPLE.TM_USER.USER_NAME IS 'ユーザ名';
COMMENT ON COLUMN SAMPLE.TM_USER.ROLE IS 'ロール';
COMMENT ON COLUMN SAMPLE.TM_USER.ACCOUNT_LOCKED IS 'ロックフラグ';
COMMENT ON COLUMN SAMPLE.TM_USER.DEL_FLG IS '論理削除フラグ';
COMMENT ON COLUMN SAMPLE.TM_USER.CREATED_AT IS '登録日時';
COMMENT ON COLUMN SAMPLE.TM_USER.CREATED_BY IS '登録者';
COMMENT ON COLUMN SAMPLE.TM_USER.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN SAMPLE.TM_USER.UPDATED_BY IS '更新者';

-- 会社マスタ
DROP TABLE IF EXISTS SAMPLE.TM_COMPANY CASCADE;
CREATE TABLE SAMPLE.TM_COMPANY (
    COMPANY_ID VARCHAR(20) PRIMARY KEY,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    DEL_FLG BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50)
);

COMMENT ON TABLE SAMPLE.TM_COMPANY IS '会社マスタ';
COMMENT ON COLUMN SAMPLE.TM_COMPANY.COMPANY_ID IS '会社ID（PK）';
COMMENT ON COLUMN SAMPLE.TM_COMPANY.COMPANY_NAME IS '会社名';
COMMENT ON COLUMN SAMPLE.TM_COMPANY.DEL_FLG IS '論理削除フラグ';
COMMENT ON COLUMN SAMPLE.TM_COMPANY.CREATED_AT IS '登録日時';
COMMENT ON COLUMN SAMPLE.TM_COMPANY.CREATED_BY IS '登録者';
COMMENT ON COLUMN SAMPLE.TM_COMPANY.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN SAMPLE.TM_COMPANY.UPDATED_BY IS '更新者';

-- ユーザ所属マスタ
DROP TABLE IF EXISTS SAMPLE.TM_USER_COMPANY CASCADE;
CREATE TABLE SAMPLE.TM_USER_COMPANY (
    USER_ID VARCHAR(50) NOT NULL,
    COMPANY_ID VARCHAR(20) NOT NULL,
    DEL_FLG BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    PRIMARY KEY (USER_ID, COMPANY_ID)
);

COMMENT ON TABLE SAMPLE.TM_USER_COMPANY IS 'ユーザ所属マスタ';
COMMENT ON COLUMN SAMPLE.TM_USER_COMPANY.USER_ID IS 'ユーザID';
COMMENT ON COLUMN SAMPLE.TM_USER_COMPANY.COMPANY_ID IS '会社ID';
COMMENT ON COLUMN SAMPLE.TM_USER_COMPANY.DEL_FLG IS '論理削除フラグ';
COMMENT ON COLUMN SAMPLE.TM_USER_COMPANY.CREATED_AT IS '登録日時';
COMMENT ON COLUMN SAMPLE.TM_USER_COMPANY.CREATED_BY IS '登録者';
COMMENT ON COLUMN SAMPLE.TM_USER_COMPANY.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN SAMPLE.TM_USER_COMPANY.UPDATED_BY IS '更新者';

-- 商品マスタ
DROP TABLE IF EXISTS SAMPLE.TM_PRODUCT CASCADE;
CREATE TABLE SAMPLE.TM_PRODUCT (
    PRODUCT_ID VARCHAR(50) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    COMPANY_ID VARCHAR(20) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    STOCK_QUANTITY INTEGER NOT NULL DEFAULT 0,
    DESCRIPTION TEXT,
    DEL_FLG BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50)
);

COMMENT ON TABLE SAMPLE.TM_PRODUCT IS '商品マスタ';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.PRODUCT_ID IS '商品ID（PK）';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.PRODUCT_NAME IS '商品名';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.COMPANY_ID IS '会社ID';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.PRICE IS '価格';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.STOCK_QUANTITY IS '在庫数';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.DESCRIPTION IS '商品説明';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.DEL_FLG IS '論理削除フラグ';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.CREATED_AT IS '登録日時';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.CREATED_BY IS '登録者';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN SAMPLE.TM_PRODUCT.UPDATED_BY IS '更新者';

-- 会社別購入可能商品承認マスタ
DROP TABLE IF EXISTS SAMPLE.TM_COMPANY_PRODUCT_AUTH CASCADE;
CREATE TABLE SAMPLE.TM_COMPANY_PRODUCT_AUTH (
    COMPANY_ID VARCHAR(20) NOT NULL,
    SALES_COMPANY_ID VARCHAR(20) NOT NULL,
    DEL_FLG BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    PRIMARY KEY (COMPANY_ID, SALES_COMPANY_ID)
);

COMMENT ON TABLE SAMPLE.TM_COMPANY_PRODUCT_AUTH IS '会社別購入可能商品承認マスタ';
COMMENT ON COLUMN SAMPLE.TM_COMPANY_PRODUCT_AUTH.COMPANY_ID IS '会社ID';
COMMENT ON COLUMN SAMPLE.TM_COMPANY_PRODUCT_AUTH.SALES_COMPANY_ID IS '販売会社ID';
COMMENT ON COLUMN SAMPLE.TM_COMPANY_PRODUCT_AUTH.DEL_FLG IS '論理削除フラグ';
COMMENT ON COLUMN SAMPLE.TM_COMPANY_PRODUCT_AUTH.CREATED_AT IS '登録日時';
COMMENT ON COLUMN SAMPLE.TM_COMPANY_PRODUCT_AUTH.CREATED_BY IS '登録者';
COMMENT ON COLUMN SAMPLE.TM_COMPANY_PRODUCT_AUTH.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN SAMPLE.TM_COMPANY_PRODUCT_AUTH.UPDATED_BY IS '更新者';

-- カートトランザクション
DROP TABLE IF EXISTS SAMPLE.TT_CART CASCADE;
CREATE TABLE SAMPLE.TT_CART (
    USER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID VARCHAR(50) NOT NULL,
    QUANTITY INTEGER NOT NULL DEFAULT 1,
    DEL_FLG BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    PRIMARY KEY (USER_ID, PRODUCT_ID)
);

COMMENT ON TABLE SAMPLE.TT_CART IS 'カートトランザクション';
COMMENT ON COLUMN SAMPLE.TT_CART.USER_ID IS 'ユーザID';
COMMENT ON COLUMN SAMPLE.TT_CART.PRODUCT_ID IS '商品ID';
COMMENT ON COLUMN SAMPLE.TT_CART.QUANTITY IS '数量';
COMMENT ON COLUMN SAMPLE.TT_CART.DEL_FLG IS '論理削除フラグ';
COMMENT ON COLUMN SAMPLE.TT_CART.CREATED_AT IS '登録日時';
COMMENT ON COLUMN SAMPLE.TT_CART.CREATED_BY IS '登録者';
COMMENT ON COLUMN SAMPLE.TT_CART.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN SAMPLE.TT_CART.UPDATED_BY IS '更新者';

-- インデックス作成
CREATE INDEX IDX_TM_USER_COMPANY_USER_ID ON SAMPLE.TM_USER_COMPANY(USER_ID);
CREATE INDEX IDX_TM_USER_COMPANY_COMPANY_ID ON SAMPLE.TM_USER_COMPANY(COMPANY_ID);
CREATE INDEX IDX_TM_PRODUCT_COMPANY_ID ON SAMPLE.TM_PRODUCT(COMPANY_ID);
CREATE INDEX IDX_TM_PRODUCT_NAME ON SAMPLE.TM_PRODUCT(PRODUCT_NAME);
CREATE INDEX IDX_TT_CART_USER_ID ON SAMPLE.TT_CART(USER_ID);
CREATE INDEX IDX_TM_COMPANY_PRODUCT_AUTH_COMPANY_ID ON SAMPLE.TM_COMPANY_PRODUCT_AUTH(COMPANY_ID);
CREATE INDEX IDX_TM_COMPANY_PRODUCT_AUTH_SALES_COMPANY_ID ON SAMPLE.TM_COMPANY_PRODUCT_AUTH(SALES_COMPANY_ID);
